global:
  scrape_interval: 50s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113']
    metrics_path: '/metrics'
  - job_name: 'php_fpm'
    static_configs:
      - targets: ['php_fpm_exporter_app1:9253', 'php_fpm_exporter_app2:9253', 'php_fpm_exporter_app3:9253']
    metrics_path: '/metrics'
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql_exporter:9104']
    metrics_path: '/metrics'
  - job_name: 'memcached'
    static_configs:
      - targets: ['memcached_exporter:9150']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
